default_platform(:ios)

require 'dotenv'
require 'fileutils'
Dotenv.load(File.expand_path('.env.beta', __dir__))

ios_dir = File.expand_path('..', __dir__)
xcodeproj_path = File.join(ios_dir, 'nuri_teacher.xcodeproj')
plist_path = File.join(ios_dir, 'nuri_teacher', 'Info.plist')
workspace_path = File.join(ios_dir, 'nuri_teacher.xcworkspace')
config_xcconfig_path = File.join(ios_dir, 'Config.xcconfig')

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    UI.message("Using API_URL: #{ENV['API_URL']}") if ENV['API_URL']
    UI.message("Using ASC_KEY_FILE: #{ENV['ASC_KEY_FILE']}") if ENV['ASC_KEY_FILE']

    asc_api_key = app_store_connect_api_key(
      key_id: ENV.fetch('ASC_KEY_ID'),
      issuer_id: ENV.fetch('ASC_ISSUER_ID'),
      key_filepath: ENV.fetch('ASC_KEY_FILE')
    )

    FileUtils.touch(config_xcconfig_path)

    match(
      type: "appstore",
      git_url: "git@github.com:rob-blasetti/signing-repo.git",
      app_identifier: "com.liquidspirit.nuriteacher",
      api_key: asc_api_key
    )

    update_app_identifier(
      xcodeproj: xcodeproj_path,
      plist_path: plist_path,
      app_identifier: "com.liquidspirit.nuriteacher"
    )

    increment_build_number(
      xcodeproj: xcodeproj_path
    )

    File.write(
      config_xcconfig_path,
      [
        "API_URL=#{ENV['API_URL']}"
      ].join("\n") + "\n"
    )

    build_app(
      workspace: workspace_path,
      scheme: "nuri_teacher",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        signingCertificate: "Apple Distribution",
        provisioningProfiles: {
          "com.liquidspirit.nuriteacher" => "match AppStore com.liquidspirit.nuriteacher"
        }
      },
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=7MGG8ZRN25 PROVISIONING_PROFILE_SPECIFIER='match AppStore com.liquidspirit.nuriteacher' CODE_SIGN_IDENTITY='Apple Distribution'"
    )

    upload_to_testflight(
      api_key: asc_api_key
    )
  end
end
